/* eslint-disable */

import hljs from 'highlight.js/lib/highlight';

// ---
// Languages supported as of highlight.js v9.17.1.
//
// We can't have a dynamic require statement below because webpack doesn't
// evaluate statements and will therefore include all languages in the final
// bundle unless webpack is additionally configured to not include the languages
// we don't intend to include.
// ---

hljs.registerLanguage('actionscript',      require('highlight.js/lib/languages/actionscript'));
hljs.registerLanguage('apache',            require('highlight.js/lib/languages/apache'));
hljs.registerLanguage('applescript',       require('highlight.js/lib/languages/applescript'));
hljs.registerLanguage('asciidoc',          require('highlight.js/lib/languages/asciidoc'));
hljs.registerLanguage('bash',              require('highlight.js/lib/languages/bash'));
hljs.registerLanguage('basic',             require('highlight.js/lib/languages/basic'));
hljs.registerLanguage('clojure',           require('highlight.js/lib/languages/clojure'));
hljs.registerLanguage('clojure-repl',      require('highlight.js/lib/languages/clojure-repl'));
hljs.registerLanguage('cmake',             require('highlight.js/lib/languages/cmake'));
hljs.registerLanguage('coffeescript',      require('highlight.js/lib/languages/coffeescript'));
hljs.registerLanguage('cpp',               require('highlight.js/lib/languages/cpp'));
hljs.registerLanguage('crystal',           require('highlight.js/lib/languages/crystal'));
hljs.registerLanguage('css',               require('highlight.js/lib/languages/css'));
hljs.registerLanguage('dart',              require('highlight.js/lib/languages/dart'));
hljs.registerLanguage('diff',              require('highlight.js/lib/languages/diff'));
hljs.registerLanguage('django',            require('highlight.js/lib/languages/django'));
hljs.registerLanguage('dns',               require('highlight.js/lib/languages/dns'));
hljs.registerLanguage('dockerfile',        require('highlight.js/lib/languages/dockerfile'));
hljs.registerLanguage('dos',               require('highlight.js/lib/languages/dos'));
hljs.registerLanguage('dsconfig',          require('highlight.js/lib/languages/dsconfig'));
hljs.registerLanguage('elixir',            require('highlight.js/lib/languages/elixir'));
hljs.registerLanguage('elm',               require('highlight.js/lib/languages/elm'));
hljs.registerLanguage('erb',               require('highlight.js/lib/languages/erb'));
hljs.registerLanguage('erlang-repl',       require('highlight.js/lib/languages/erlang-repl'));
hljs.registerLanguage('erlang',            require('highlight.js/lib/languages/erlang'));
hljs.registerLanguage('excel',             require('highlight.js/lib/languages/excel'));
hljs.registerLanguage('fortran',           require('highlight.js/lib/languages/fortran'));
hljs.registerLanguage('fsharp',            require('highlight.js/lib/languages/fsharp'));
hljs.registerLanguage('gherkin',           require('highlight.js/lib/languages/gherkin'));
hljs.registerLanguage('go',                require('highlight.js/lib/languages/go'));
hljs.registerLanguage('gradle',            require('highlight.js/lib/languages/gradle'));
hljs.registerLanguage('groovy',            require('highlight.js/lib/languages/groovy'));
hljs.registerLanguage('haml',              require('highlight.js/lib/languages/haml'));
hljs.registerLanguage('handlebars',        require('highlight.js/lib/languages/handlebars'));
hljs.registerLanguage('haskell',           require('highlight.js/lib/languages/haskell'));
hljs.registerLanguage('htmlbars',          require('highlight.js/lib/languages/htmlbars'));
hljs.registerLanguage('http',              require('highlight.js/lib/languages/http'));
hljs.registerLanguage('ini',               require('highlight.js/lib/languages/ini'));
hljs.registerLanguage('java',              require('highlight.js/lib/languages/java'));
hljs.registerLanguage('javascript',        require('highlight.js/lib/languages/javascript'));
hljs.registerLanguage('json',              require('highlight.js/lib/languages/json'));
hljs.registerLanguage('julia',             require('highlight.js/lib/languages/julia'));
hljs.registerLanguage('julia-repl',        require('highlight.js/lib/languages/julia-repl'));
hljs.registerLanguage('kotlin',            require('highlight.js/lib/languages/kotlin'));
hljs.registerLanguage('ldif',              require('highlight.js/lib/languages/ldif'));
hljs.registerLanguage('less',              require('highlight.js/lib/languages/less'));
hljs.registerLanguage('lisp',              require('highlight.js/lib/languages/lisp'));
hljs.registerLanguage('livescript',        require('highlight.js/lib/languages/livescript'));
hljs.registerLanguage('lua',               require('highlight.js/lib/languages/lua'));
hljs.registerLanguage('makefile',          require('highlight.js/lib/languages/makefile'));
hljs.registerLanguage('markdown',          require('highlight.js/lib/languages/markdown'));
hljs.registerLanguage('mathematica',       require('highlight.js/lib/languages/mathematica'));
hljs.registerLanguage('matlab',            require('highlight.js/lib/languages/matlab'));
hljs.registerLanguage('perl',              require('highlight.js/lib/languages/perl'));
hljs.registerLanguage('nginx',             require('highlight.js/lib/languages/nginx'));
hljs.registerLanguage('nix',               require('highlight.js/lib/languages/nix'));
hljs.registerLanguage('objectivec',        require('highlight.js/lib/languages/objectivec'));
hljs.registerLanguage('ocaml',             require('highlight.js/lib/languages/ocaml'));
hljs.registerLanguage('pgsql',             require('highlight.js/lib/languages/pgsql'));
hljs.registerLanguage('php',               require('highlight.js/lib/languages/php'));
hljs.registerLanguage('plaintext',         require('highlight.js/lib/languages/plaintext'));
hljs.registerLanguage('powershell',        require('highlight.js/lib/languages/powershell'));
hljs.registerLanguage('prolog',            require('highlight.js/lib/languages/prolog'));
hljs.registerLanguage('python',            require('highlight.js/lib/languages/python'));
hljs.registerLanguage('r',                 require('highlight.js/lib/languages/r'));
hljs.registerLanguage('reasonml',          require('highlight.js/lib/languages/reasonml'));
hljs.registerLanguage('ruby',              require('highlight.js/lib/languages/ruby'));
hljs.registerLanguage('rust',              require('highlight.js/lib/languages/rust'));
hljs.registerLanguage('scala',             require('highlight.js/lib/languages/scala'));
hljs.registerLanguage('scss',              require('highlight.js/lib/languages/scss'));
hljs.registerLanguage('shell',             require('highlight.js/lib/languages/shell'));
hljs.registerLanguage('smalltalk',         require('highlight.js/lib/languages/smalltalk'));
hljs.registerLanguage('sql',               require('highlight.js/lib/languages/sql'));
hljs.registerLanguage('swift',             require('highlight.js/lib/languages/swift'));
hljs.registerLanguage('typescript',        require('highlight.js/lib/languages/typescript'));
hljs.registerLanguage('vbnet',             require('highlight.js/lib/languages/vbnet'));
hljs.registerLanguage('vbscript',          require('highlight.js/lib/languages/vbscript'));
hljs.registerLanguage('vim',               require('highlight.js/lib/languages/vim'));
hljs.registerLanguage('yaml',              require('highlight.js/lib/languages/yaml'));
hljs.registerLanguage('xml',               require('highlight.js/lib/languages/xml'));

// ---
// Uncomment below to include that language in the final build
// ---

// hljs.registerLanguage('1c',             require('highlight.js/lib/languages/1c'));
// hljs.registerLanguage('abnf',           require('highlight.js/lib/languages/abnf'));
// hljs.registerLanguage('accesslog',      require('highlight.js/lib/languages/accesslog'));
// hljs.registerLanguage('ada',            require('highlight.js/lib/languages/ada'));
// hljs.registerLanguage('angelscript',    require('highlight.js/lib/languages/angelscript'));
// hljs.registerLanguage('arcade',         require('highlight.js/lib/languages/arcade'));
// hljs.registerLanguage('arduino',        require('highlight.js/lib/languages/arduino'));
// hljs.registerLanguage('armasm',         require('highlight.js/lib/languages/armasm'));
// hljs.registerLanguage('aspectj',        require('highlight.js/lib/languages/aspectj'));
// hljs.registerLanguage('autohotkey',     require('highlight.js/lib/languages/autohotkey'));
// hljs.registerLanguage('autoit',         require('highlight.js/lib/languages/autoit'));
// hljs.registerLanguage('avrasm',         require('highlight.js/lib/languages/avrasm'));
// hljs.registerLanguage('awk',            require('highlight.js/lib/languages/awk'));
// hljs.registerLanguage('axapta',         require('highlight.js/lib/languages/axapta'));
// hljs.registerLanguage('bnf',            require('highlight.js/lib/languages/bnf'));
// hljs.registerLanguage('brainfuck',      require('highlight.js/lib/languages/brainfuck'));
// hljs.registerLanguage('cal',            require('highlight.js/lib/languages/cal'));
// hljs.registerLanguage('capnproto',      require('highlight.js/lib/languages/capnproto'));
// hljs.registerLanguage('ceylon',         require('highlight.js/lib/languages/ceylon'));
// hljs.registerLanguage('clean',          require('highlight.js/lib/languages/clean'));
// hljs.registerLanguage('coq',            require('highlight.js/lib/languages/coq'));
// hljs.registerLanguage('cos',            require('highlight.js/lib/languages/cos'));
// hljs.registerLanguage('crmsh',          require('highlight.js/lib/languages/crmsh'));
// hljs.registerLanguage('cs',             require('highlight.js/lib/languages/cs'));
// hljs.registerLanguage('csp',            require('highlight.js/lib/languages/csp'));
// hljs.registerLanguage('d',              require('highlight.js/lib/languages/d'));
// hljs.registerLanguage('delphi',         require('highlight.js/lib/languages/delphi'));
// hljs.registerLanguage('dts',            require('highlight.js/lib/languages/dts'));
// hljs.registerLanguage('dust',           require('highlight.js/lib/languages/dust'));
// hljs.registerLanguage('ebnf',           require('highlight.js/lib/languages/ebnf'));
// hljs.registerLanguage('fix',            require('highlight.js/lib/languages/fix'));
// hljs.registerLanguage('flix',           require('highlight.js/lib/languages/flix'));
// hljs.registerLanguage('gams',           require('highlight.js/lib/languages/gams'));
// hljs.registerLanguage('gauss',          require('highlight.js/lib/languages/gauss'));
// hljs.registerLanguage('gcode',          require('highlight.js/lib/languages/gcode'));
// hljs.registerLanguage('glsl',           require('highlight.js/lib/languages/glsl'));
// hljs.registerLanguage('gml',            require('highlight.js/lib/languages/gml'));
// hljs.registerLanguage('golo',           require('highlight.js/lib/languages/golo'));
// hljs.registerLanguage('haxe',           require('highlight.js/lib/languages/haxe'));
// hljs.registerLanguage('hsp',            require('highlight.js/lib/languages/hsp'));
// hljs.registerLanguage('hy',             require('highlight.js/lib/languages/hy'));
// hljs.registerLanguage('inform7',        require('highlight.js/lib/languages/inform7'));
// hljs.registerLanguage('irpf90',         require('highlight.js/lib/languages/irpf90'));
// hljs.registerLanguage('isbl',           require('highlight.js/lib/languages/isbl'));
// hljs.registerLanguage('jboss-cli',      require('highlight.js/lib/languages/jboss-cli'));
// hljs.registerLanguage('lasso',          require('highlight.js/lib/languages/lasso'));
// hljs.registerLanguage('leaf',           require('highlight.js/lib/languages/leaf'));
// hljs.registerLanguage('livecodeserver', require('highlight.js/lib/languages/livecodeserver'));
// hljs.registerLanguage('llvm',           require('highlight.js/lib/languages/llvm'));
// hljs.registerLanguage('lsl',            require('highlight.js/lib/languages/lsl'));
// hljs.registerLanguage('maxima',         require('highlight.js/lib/languages/maxima'));
// hljs.registerLanguage('mel',            require('highlight.js/lib/languages/mel'));
// hljs.registerLanguage('mercury',        require('highlight.js/lib/languages/mercury'));
// hljs.registerLanguage('mipsasm',        require('highlight.js/lib/languages/mipsasm'));
// hljs.registerLanguage('mizar',          require('highlight.js/lib/languages/mizar'));
// hljs.registerLanguage('mojolicious',    require('highlight.js/lib/languages/mojolicious'));
// hljs.registerLanguage('monkey',         require('highlight.js/lib/languages/monkey'));
// hljs.registerLanguage('moonscript',     require('highlight.js/lib/languages/moonscript'));
// hljs.registerLanguage('n1ql',           require('highlight.js/lib/languages/n1ql'));
// hljs.registerLanguage('nimrod',         require('highlight.js/lib/languages/nimrod'));
// hljs.registerLanguage('nsis',           require('highlight.js/lib/languages/nsis'));
// hljs.registerLanguage('openscad',       require('highlight.js/lib/languages/openscad'));
// hljs.registerLanguage('oxygene',        require('highlight.js/lib/languages/oxygene'));
// hljs.registerLanguage('parser3',        require('highlight.js/lib/languages/parser3'));
// hljs.registerLanguage('pf',             require('highlight.js/lib/languages/pf'));
// hljs.registerLanguage('pony',           require('highlight.js/lib/languages/pony'));
// hljs.registerLanguage('processing',     require('highlight.js/lib/languages/processing'));
// hljs.registerLanguage('profile',        require('highlight.js/lib/languages/profile'));
// hljs.registerLanguage('properties',     require('highlight.js/lib/languages/properties'));
// hljs.registerLanguage('protobuf',       require('highlight.js/lib/languages/protobuf'));
// hljs.registerLanguage('puppet',         require('highlight.js/lib/languages/puppet'));
// hljs.registerLanguage('purebasic',      require('highlight.js/lib/languages/purebasic'));
// hljs.registerLanguage('q',              require('highlight.js/lib/languages/q'));
// hljs.registerLanguage('qml',            require('highlight.js/lib/languages/qml'));
// hljs.registerLanguage('rib',            require('highlight.js/lib/languages/rib'));
// hljs.registerLanguage('roboconf',       require('highlight.js/lib/languages/roboconf'));
// hljs.registerLanguage('routeros',       require('highlight.js/lib/languages/routeros'));
// hljs.registerLanguage('rsl',            require('highlight.js/lib/languages/rsl'));
// hljs.registerLanguage('ruleslanguage',  require('highlight.js/lib/languages/ruleslanguage'));
// hljs.registerLanguage('sas',            require('highlight.js/lib/languages/sas'));
// hljs.registerLanguage('scheme',         require('highlight.js/lib/languages/scheme'));
// hljs.registerLanguage('scilab',         require('highlight.js/lib/languages/scilab'));
// hljs.registerLanguage('smali',          require('highlight.js/lib/languages/smali'));
// hljs.registerLanguage('sml',            require('highlight.js/lib/languages/sml'));
// hljs.registerLanguage('sqf',            require('highlight.js/lib/languages/sqf'));
// hljs.registerLanguage('stan',           require('highlight.js/lib/languages/stan'));
// hljs.registerLanguage('stata',          require('highlight.js/lib/languages/stata'));
// hljs.registerLanguage('step21',         require('highlight.js/lib/languages/step21'));
// hljs.registerLanguage('stylus',         require('highlight.js/lib/languages/stylus'));
// hljs.registerLanguage('subunit',        require('highlight.js/lib/languages/subunit'));
// hljs.registerLanguage('taggerscript',   require('highlight.js/lib/languages/taggerscript'));
// hljs.registerLanguage('tap',            require('highlight.js/lib/languages/tap'));
// hljs.registerLanguage('tcl',            require('highlight.js/lib/languages/tcl'));
// hljs.registerLanguage('tex',            require('highlight.js/lib/languages/tex'));
// hljs.registerLanguage('thrift',         require('highlight.js/lib/languages/thrift'));
// hljs.registerLanguage('tp',             require('highlight.js/lib/languages/tp'));
// hljs.registerLanguage('twig',           require('highlight.js/lib/languages/twig'));
// hljs.registerLanguage('vala',           require('highlight.js/lib/languages/vala'));
// hljs.registerLanguage('vbscript-html',  require('highlight.js/lib/languages/vbscript-html'));
// hljs.registerLanguage('verilog',        require('highlight.js/lib/languages/verilog'));
// hljs.registerLanguage('vhdl',           require('highlight.js/lib/languages/vhdl'));
// hljs.registerLanguage('x86asm',         require('highlight.js/lib/languages/x86asm'));
// hljs.registerLanguage('xl',             require('highlight.js/lib/languages/xl'));
// hljs.registerLanguage('xquery',         require('highlight.js/lib/languages/xquery'));
// hljs.registerLanguage('zephir',         require('highlight.js/lib/languages/zephir'));

export default hljs;
