---
title: ARPobservation now on CRAN
author: 'James'
date: '2014-05-31'
slug: ARPobservation-now-on-CRAN
categories: []
tags:
  - behavioral observation
  - R
header:
  caption: ''
  image: ''
---

Version 1.0 of the [ARPobservation package](https://cran.r-project.org/web/packages/ARPobservation/) is now available on the Comprehensive R Archive Network. This makes it [even easier to install]({{site.url}}/getting-started-with-ARPobservation). Here's the package description:

__ARPobservation: Tools for simulating different methods of observing behavior based on alternating renewal processes__

_ARPobservation provides a set of tools for simulating data based on direct observation of behavior. It works by first simulating a behavior stream based on an alternating renewal process, given specified distributions of event durations and interim times. Different procedures for recording data can then be applied to the simulated behavior stream. Currently, functions are provided for the following recording methods: continuous duration recording, event counting, momentary time sampling, partial interval recording, and whole interval recording._
