---
title: "New article: Four methods for analyzing PIR data"
author: 'James'
date: '2015-02-11'
slug: Four-methods-for-analyzing-PIR-data
categories: []
tags:
  - behavioral observation
  - single-case research
header:
  caption: ''
  image: ''
---

My article with Daniel Swan, "Four methods for analyzing partial interval recording data, with application to single-case research" has been accepted for publication in Multivariate Behavioral Research. In an extension of my earlier paper on [measurement-comparable effect sizes]({{ site.url }}/files/Measurement-comparable-ES.pdf) for single-case studies, this article provides some approaches to estimating effect sizes from single-case studies that use partial interval or whole interval recording to measure behavioral outcomes. The full abstract is below. [Preprint]({{ site.url }}/files/4-PIR-methods-MBR.pdf) and [supporting materials]({{ site.url }}/files/4-PIR-Methods-Appendix.pdf) are available. R functions that implement the proposed methods are available in the package [ARPobservation](https://cran.r-project.org/web/packages/ARPobservation/).

_Partial interval recording is a procedure for collecting measurements during direct observation of behavior. It is used in several areas of educational and psychological research, particularly in connection with single-case research. Measurements collected using partial interval recording suffer from construct invalidity because they are not readily interpretable in terms of the underlying characteristics of the behavior. Using an alternating renewal process model for the behavior under observation, we demonstrate that ignoring the construct invalidity of PIR data can produce misleading inferences, such as inferring that an intervention reduces the prevalence of an undesirable behavior when in fact it has the opposite effect. We then propose four different methods for analyzing PIR summary measurements, each of which can be used to draw inferences about interpretable behavioral parameters. We demonstrate the methods by applying them to data from two single-case studies of problem behavior._
