---
layout: post
title: Covariate interactions in regression discontinuity designs
date: January 22, 2016
---

In the standard presentation of sharp regression discontinuity designs (RDDs), the only variables involved are 

1. The outcome variable (call it $Y$),
2. Treatment assignment (call it $T$, with $T = 1$ for units that are treated and $T = 0$ otherwise), and
3. The running variable (call it $R$), which perfectly determines treatment status as $T = I(R > 0)$ (assuming that $R$ is centered at the threshold of treatment assignment). 

(In fuzzy RDDs, where treatment compliance may be imperfect, there is a further variable (call it $S$) that captures actual treatment receipt. I'll ignore this for the moment.) Given a sample of $n$ observations $(y_i, t_i, r_i)_{i=1}^n$, the average treatment effect at the threshold is typically estimated using weighted least squares estimation of

$$y_i = \beta_0 + \beta_1 r_i + \beta_2 t_i + \beta_3 r_i t_i + \epsilon_i,$$

with weights assigned using some kernel measure of distance from the threshold on the running variable. The coefficient $\beta_2$ corresponds to the threshold-average treatment effect. 

In practice, however, it is quite common for analysts to include additional covariates in the model. Doing so is not necessary for treatment effect identification, but can be useful for purposes of improving precision. For example, Cortes, Goodman, and Nomi (2015) use an RDD to estimate the effects of assigning low-performing 9th graders to double-dose algebra. Their main specifications include controls for student gender, race/ethnicity, free/reduced-price lunch status, etc. In the analysis that I'm working on, the data come from students nested within multiple schools, and so it seems sensible to include fixed effects for each school. There's a direct analogy here to simple randomized experiments: the basic difference in means provides a randomization-unbiased estimate of the sample average treatment effect, but in practice it can be awfully useful to use an estimate from a model with additional covariates. 

### References 

[Cortes, K. E., Goodman, J. S., & Nomi, T. (2015)](http://doi.org/10.3368/jhr.50.1.108). Intensive Math Instruction and Educational Attainment Long-Run Impacts of Double-Dose Algebra. Journal of Human Resources, 50(1), 108-158.