---
title: "New article: Design-comparable effect sizes in multiple baseline designs: A general modeling framework"
authors:
- admin
date: '2014-07-20'
slug: design-comparable-effect-sizes-in-multiple-baseline-designs
categories: []
tags:
  - single-case design
  - effect size
  - hierarchical models
  - design-comparable SMD
header:
  caption: ''
  image: ''
---

My article with Larry Hedges and Will Shadish, titled "Design-comparable effect sizes in multiple baseline designs: A general modeling framework" has been accepted at Journal of Educational and Behavioral Statistics. The abstract is below. Here's the article at [the journal website](http://doi.org/10.3102/1076998614547577). [Postprint](/files/Effect-sizes-in-multiple-baseline-designs-JEBS.pdf) and [supporting materials](/files/Effect-sizes-in-multiple-baseline-designs-Simulation-results.pdf) are available. An R package that implements the proposed methods is [available here](/getting-started-with-scdhlm/).

_In single-case research, the multiple baseline design is a widely used approach for evaluating the effects of interventions on individuals. Multiple baseline designs involve repeated measurement of outcomes over time and the controlled introduction of a treatment at different times for different individuals. This article outlines a general approach for defining effect sizes in multiple baseline designs that are directly comparable to the standardized mean difference from a between-subjects randomized experiment. The target, design-comparable effect size parameter can be estimated using restricted maximum likelihood together with a small-sample correction analogous to Hedges’ g. The approach is demonstrated using hierarchical linear models that include baseline time trends and treatment-by-time interactions. A simulation compares the performance of the proposed estimator to that of an alternative, and an application illustrates the model-fitting process._
