---
title: Getting started with ARPobservation
authors:
- admin
date: '2013-10-24'
slug: Getting-started-with-ARPobservation
categories: []
tags:
  - behavioral observation
  - simulation
  - Rstats
header:
  caption: ''
  image: ''
---

**UPDATED 5/29/2014 after posting the package to CRAN**

Here are step-by-step instructions on how to download and install ARPobservation. For the time being, ARPobservation is available as a pre-compiled binary for Windows. For Mac/Linux, you'll have to download the source from Github. 

1. [Download](http://cran.us.r-project.org/) and install R. R is free, open-source software that is used by many data analysts and statisticians. ARPobservation is a contributed package that runs within R, so you'll need to get the base software first.

2. (Optional but recommended) [Download](http://www.rstudio.com/) and install RStudio, which is a very nice front-end interface to R.

3. Open R or RStudio and type the following sequence of commands in the console:

  ```{r eval = FALSE}
  install.packages("ARPobservation")
  library(ARPobservation)
  ```

You'll only need to do the above once. Once you've got the package installed, type the following in order to access the package within an R session: `library(ARPobservation)`. 

To open the package documentation, type `package?ARPobservation`. To access the documentation for an individual function in this package, just type `?` followed by the name of the function. For instance, one of the main functions in the package is called `r_behavior_stream`; to access its documentation, type `?r_behavior_stream`.
