---
layout: post
title: Too Much Maths, Too Little History
header-includes:
    - \usepackage {hyperref}
    - \hypersetup {colorlinks = true, linkcolor = red, urlcolor = red}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

One hundred and thirty years ago, there was the ‘methodenstreit’. That means ‘a battle over methods’ in German and it described the contemporary debate in economics. For over a decade, the German Historical School and the Austrian School argued over the correct way to study economics, and whether that constituted detailed historical investigation or mathematized logic.

In 2015, LSESU Economics Society held their ‘Too Much Maths, Too Little History' debate. Assembled in the Sheikh Zayed Theatre, armed with microphones and a panel of speakers, we had our own little Methodenstreit. And, the battle goes on. This debate has echoed throughout my time at LSE. 

However, these discussions rarely reach a satisfying conclusion. I have to assume that future generations of students will solve as many Lagrangians as we have. Of course, I have to assume a lot of things. So I’m writing this commentary on our Methodenstreit to clarify some points that we often trip up on. By signposting these, I hope to point us towards a more productive debate.

## A Tug of War

Imagine a game of tug of war. On one side stand the mathematicians, with the slogan ‘maths is just the language of economics’ embroidered across their jerseys. The historical team take the other side. ‘But you need more context’ and ‘the model is too simple’ are among their most popular chants and they are guaranteed crowd-pleasers. The audience cheers every time. The game starts and they begin tugging but, quite soon, both teams realise that they have no interest in dragging the other across the line. They continue trash talking a little but no one pulls too hard in either direction. A young econometrician, waiting eagerly on the bench, is then called to sub in. But when the whistle blows, she realises that she doesn’t know which team she’s on. She loves the data, a staunch empiricist like her historical colleagues, but the mathematicians taught her everything. Is it not their models that she estimates? Now everyone stops. They’re all looking at each other. ‘You look at old data, too? Why aren’t you on my team? Wait, am I on your team?’ Unclear on how to proceed or even where to stand, they each concede that the other side make valid points and retreat back to their offices.

If you haven’t watched the ‘Too Much Maths, Too Little History’ debate, that would be my summary\footnote{But also, you can click \href{https://youtu.be/6rXBBqMmIP8}{here} to watch it.}. It motivates a few important points and I will explore them further.

## Too Much Maths? What is Maths?

A poor definition of terms confounds this debate. In general, the argument for more history is premised on the logic that bad assumptions are endemic to mathematical economics and that historical methods resolve this. At some point in the conversation, ‘maths’ becomes a dirty word. It’s synonymous with ‘a simplifying abstraction’ but has negative connotations. As such, the question of ‘maths vs. history’ rapidly shifts to one of ‘(bad) theory vs. empiricism’. But, in an age of data-driven economics, this is a straw man argument. Facing modern applied economics, critics often point to the failures of Neoclassical theory from the ‘70s. This conflation of mathematical methods – structural models, game theory, econometrics, etc – is a fundamental confusion that needs to be corrected. The shift in the debate and a misconception of maths makes it very difficult to hold this conversation and it’s why the econometrician, standing on the side-lines, couldn’t choose a team.

That being said, I’d still offer a defence for the theories. Specifically, and contrary to the common critique, relying on assumptions doesn’t make a theory bad. Rather, relying on bad assumptions makes a theory bad. Calling them out and interrogating them is important – all knowledge demands scepticism – but their existence is not in itself a catch-all failure of modern economics. Importantly, assumptions give us traction. When everything is changing and everyone is connected, it’s hard to even imagine the causes of things. So, to predict the effect of some event, it’s helpful to hold some things still and to tie some other things together.  And, at the forefront of the field, economists keep getting answers while holding fewer things still. Maybe they let them change over time, or across space, or let them move around a fixed point. They’re also finding better ways to tie those other things together. Parameterising humanness is impossible but behavioural economists, in particular, are making strides. Of course, there are aspects of our identity and our relationships and our experiences that cannot be summarised by a vector of relative prices. I know. But, for answering our questions, economists deserve more credit. Assumptions aren’t inherently bad and we’re getting good at making them less bad.

## Too Little History?

Maybe you’re thinking that this defence is pointless. The proposition was not to replace maths, it was only to offer more history. There’s some truth here. The typical economics undergraduate needn’t take a module in economic history or history of economic thought, unless they choose to. We could be looking at a generation of better economists if we did. That being said, I reject the argument that our education was entirely ahistorical.

An interested student can pick their outside options from any department and, in third year, modules in the history and the philosophy of economics are available. Even our \href{https://www.lse.ac.uk/resources/calendar2020-2021/courseGuides/EC/2020_EC210.htm}{intermediate macro} class, taken by around 650 students each year, is shot through with history. We learn the Malthusian Growth Model, which was penned in 1798, and then we do the Solow model, the 20th century upgrade. We see how Keynes modelled the demand for money and how this subsequently became one side of the IS-LM model, which synthesised Keynesianism with Neoclassical theories. This takes us to the Philips Curve, how it broke down in the 1970s and the policy questions that this raised. We go from hyperinflation in Weimar Germany to the rise of Bitcoin, from the Great Depression to the Euro Crisis. 

Framing is important. It doesn’t feel so historical when you’re just trying to solve for $dy/dx$ (assuming $N$ is constant). But maybe the issue isn’t that the model takes $N$ as given. Perhaps it’s us taking the models as given. Perhaps we should be reading our course pack as a 200-year evolution of economic thought, intertwined with economic history. I think we’re learning more history than we realise.


## Wait, What is Economics?

Until I sat down to write this, I hadn’t considered the range of methods that we find within economics. Macro and micro answer different questions, using different information. It makes sense that the importance of history is also different. As such, homogenising ‘economics’ in the battle over methods creates another confusion in the debate.

When causal questions define research, microeconomic settings are much easier to navigate. For example, we can conduct experiments or, at least, find natural experiments. State borders, policy changes and eligibility cut-offs each give us (almost) random variation in our treatment and, thus, a way to claim causality. A light bulb above a microeconomist’s head switches on when they hear any of those words. Macroeconomists, on the other hand, don’t get that. It all happens at the same time, it’s all endogenous and it all moves together. Conditions shape research, which shapes policy – which, in turn, shapes conditions. 

For this reason, I think that macro has more to gain from history than micro. It affords us a catalogue of case studies, pertaining to every condition that we’ve documented. In the absence of clear treatments and controls, history gives us a subset of potential outcomes. We don’t know what will happen but we know what happened before and this is why it may or may not happen again. 

At this point we encounter a particularly thorny question - what is economics? If a tree falls in a forest but it can’t be expressed as a system of equations, does it make a sound? If historical knowledge cannot be formalised, does it constitute economics? (According to the Austrian School, it doesn’t.) Underwhelmingly, I won’t be answering this question. Instead, my key takeaway is two sizable steps behind this; when we have these debates, we need to separate the different fields within economics, given that they adopt different methods and face different pitfalls.


## Is History Better?

It’s dangerous to valorise history as the antidote to abstraction. Firstly, everything that we do is done with assumptions, history included. Even our choice of where to look in history is an unknown function of our unknown biases. It’s a hard problem to solve. With maths, however, there’s an elegance of writing in a language that writes back immediately, telling you what you just took for granted. You don’t get that from prose.

Secondly, from my knowledge, there isn’t a coherent historical framework to follow. If there is ‘too little history’, how do we get more and what do we do with it? Should we be fitting historical data to our models? Or should we be developing theories from historical evidence? Or is it just that everything we do should be imbued with a greater awareness of our past? Without pinning this down, the proposition is too vague to reach a meaningful conclusion.


## History and the Future

There wasn’t an official winner of the Methodenstreit but, given where we are now, it looks like the Austrians are winning. The discipline splintered slightly at the time and efforts were made to toe the line between approaches so, when Alfred Marshall wrote the Principles of Economics (1890), he relegated the equations to the footnotes. Now, however, those fill our textbooks. 

I don’t expect us to reach a consensus but my aim was to clarify some misconceptions and, in doing so, facilitate a more coherent discussion. I’ll conclude with five points that should preclude the confusion that prematurely ends our debates.


* Empiricism does not belong to either side $\implies$ Don’t try to win by claiming it

*	Theory is not inherently useless $\implies$ Avoid hasty generalisations of modern theory

* Our macro course does teach history $\implies$ Approach courses  with a historical perspective

* Different fields in economics require different sets of methods $\implies$Separate debates accordingly

* Critique is only constructive if we’re specifying an alternative $\implies$Specify a framework for incorporating more history

