// You can reproduce this figure in Node.js with the following code!

// Learn about API authentication here: https://plot.ly/nodejs/getting-started
// Find your api_key here: https://plot.ly/settings/api

var plotly = require('plotly')('username', 'api_key');
var trace1 = {
  x: ["1910", "1920", "1930", "1940", "1950", "1960", "1970", "1980", "1990", "2000", "2010"], 
  y: ["7.6", "7.6", "9.9", "11.3", "13.5", "15.9", "17.5", "19.5", "21.4", "22.5", "23.4"], 
  name: "West", 
  marker: {color: "rgb(77, 135, 198)"}, 
  type: "bar"
};
var trace2 = {
  x: ["1910", "1920", "1930", "1940", "1950", "1960", "1970", "1980", "1990", "2000", "2010"], 
  y: ["31.3", "31.3", "30.6", "31.0", "30.7", "30.6", "30.8", "32.6", "34.3", "35.4", "37.0"], 
  name: "South", 
  marker: {color: "rgb(212, 218, 238)"}, 
  type: "bar"
};
var trace3 = {
  x: ["1910", "1920", "1930", "1940", "1950", "1960", "1970", "1980", "1990", "2000", "2010"], 
  y: ["32.9", "32.9", "31.5", "30.1", "29.5", "28.7", "27.8", "26.0", "24.1", "23.0", "21.6"], 
  name: "Midwest", 
  marker: {color: "rgb(225, 165, 162)"}, 
  type: "bar"
};
var trace4 = {
  x: ["1910", "1920", "1930", "1940", "1950", "1960", "1970", "1980", "1990", "2000", "2010"], 
  y: ["28.3", "28.3", "28.0", "27.6", "26.3", "24.8", "23.9", "21.8", "20.2", "19.1", "17.9"], 
  name: "Northeast", 
  marker: {color: "rgb(197, 62, 81)"}, 
  type: "bar"
};
var data = [trace1, trace2, trace3, trace4];
var layout = {
  title: "<br>Percentage Distribution of Seats in the U.S. House of Representatives by Region: 1910 to 2010", 
  titlefont: {
    family: "", 
    size: 0, 
    color: ""
  }, 
  font: {
    family: "Balto, sans-serif", 
    size: 12, 
    color: "#444"
  }, 
  showlegend: true, 
  autosize: false, 
  width: 850, 
  height: 625, 
  xaxis: {
    title: "Source & Data: <a href="http://www.census.gov/prod/cen2010/briefs/c2010br-08.pdf">U.S. Census Bureau</a><br><i>After the 2010 apportionment, the South will maintain the largest share 
of House<br>seats among all four regions, as it has since 1940. PG. 5, Census Brief.</i>", 
    titlefont: {
      family: "", 
      size: 0, 
      color: ""
    }, 
    range: [1905, 2015], 
    domain: [0, 1], 
    type: "linear", 
    rangemode: "normal", 
    autorange: true, 
    showgrid: false, 
    zeroline: false, 
    showline: false, 
    autotick: true, 
    nticks: 12, 
    ticks: "", 
    showticklabels: true, 
    tick0: 0, 
    dtick: 10, 
    ticklen: 5, 
    tickwidth: 1, 
    tickcolor: "#444", 
    tickangle: "auto", 
    tickfont: {
      family: "", 
      size: 0, 
      color: ""
    }, 
    exponentformat: "B", 
    showexponent: "all", 
    mirror: false, 
    gridcolor: "#eee", 
    gridwidth: 1, 
    zerolinecolor: "#444", 
    zerolinewidth: 1, 
    linecolor: "#444", 
    linewidth: 1, 
    anchor: "y", 
    overlaying: false, 
    position: 0
  }, 
  yaxis: {
    title: "", 
    titlefont: {
      family: "", 
      size: 0, 
      color: ""
    }, 
    range: [0, 105.368421053], 
    domain: [0, 1], 
    type: "linear", 
    rangemode: "normal", 
    autorange: true, 
    showgrid: false, 
    zeroline: true, 
    showline: false, 
    autotick: true, 
    nticks: 0, 
    ticks: "", 
    showticklabels: false, 
    tick0: 0, 
    dtick: 20, 
    ticklen: 5, 
    tickwidth: 1, 
    tickcolor: "#444", 
    tickangle: "auto", 
    tickfont: {
      family: "", 
      size: 0, 
      color: ""
    }, 
    exponentformat: "B", 
    showexponent: "all", 
    mirror: false, 
    gridcolor: "#eee", 
    gridwidth: 1, 
    zerolinecolor: "#444", 
    zerolinewidth: 1, 
    linecolor: "#444", 
    linewidth: 1, 
    anchor: "x", 
    overlaying: false, 
    position: 0
  }, 
  legend: {
    x: 0.998435054773, 
    y: 0.959523809524, 
    traceorder: "reversed", 
    font: {
      family: "", 
      size: 0, 
      color: ""
    }, 
    bgcolor: "rgba(255, 255, 255, 0)", 
    bordercolor: "#444", 
    borderwidth: 0, 
    xanchor: "left", 
    yanchor: "top"
  }, 
  annotations: [
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "7.6", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: -36, 
      ay: 116.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "7.6", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 24, 
      ay: 116.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "9.9", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 85, 
      ay: 110.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "11.3", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 143, 
      ay: 100.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "13.5", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 203, 
      ay: 88.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "15.9", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 261, 
      ay: 80.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "17.5", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 320, 
      ay: 72.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "19.5", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 380, 
      ay: 63.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "21.4", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 440, 
      ay: 55.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "22.5", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 501, 
      ay: 50.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "23.4", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 559, 
      ay: 45.9921875, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1912.00605144, 
      y: 24.9806031934, 
      xref: "x", 
      yref: "y", 
      text: "31.3", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: -12, 
      ay: -39.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "31.3", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 24, 
      ay: -11.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "30.6", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 85, 
      ay: -22.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "31.0", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 144, 
      ay: -32.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "30.7", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 205, 
      ay: -43.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "30.6", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 262, 
      ay: -50.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "30.8", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 321, 
      ay: -58.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "32.6", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 382, 
      ay: -73.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "34.3", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 441, 
      ay: -89.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "35.4", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 503, 
      ay: -100.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "37.0", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 561, 
      ay: -109.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "32.9", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: -37, 
      ay: -153.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "32.9", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 24, 
      ay: -154.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "31.5", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 83, 
      ay: -157.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "30.1", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 145, 
      ay: -160.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "29.5", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 204, 
      ay: -165.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "28.7", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 264, 
      ay: -172.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "27.8", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 325, 
      ay: -175.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "26.0", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 382, 
      ay: -184.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "24.1", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 439, 
      ay: -190.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "23.0", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 500, 
      ay: -193.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "21.6", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: ""
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 560, 
      ay: -198.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "28.3", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: -37, 
      ay: -275.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "28.3", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 25, 
      ay: -275.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "28.0", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 86, 
      ay: -275.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "27.6", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 144, 
      ay: -276.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "26.3", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 204, 
      ay: -276.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "24.8", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 264, 
      ay: -276.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "23.9", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 322, 
      ay: -277.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "21.8", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 381, 
      ay: -278.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "20.2", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 440, 
      ay: -278.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "19.1", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 500, 
      ay: -278.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }, 
    {
      x: 1916, 
      y: 31.6105263158, 
      xref: "x", 
      yref: "y", 
      text: "17.9", 
      showarrow: true, 
      font: {
        family: "", 
        size: 0, 
        color: "rgb(255, 255, 255)"
      }, 
      xanchor: "auto", 
      yanchor: "auto", 
      align: "center", 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      arrowcolor: "rgba(68, 68, 68, 0)", 
      ax: 559, 
      ay: -278.0078125, 
      textangle: 0, 
      bordercolor: "", 
      borderwidth: 1, 
      borderpad: 1, 
      bgcolor: "rgba(0,0,0,0)", 
      opacity: 1
    }
  ], 
  margin: {
    l: 80, 
    r: 80, 
    b: 80, 
    t: 100, 
    pad: 0, 
    autoexpand: true
  }, 
  paper_bgcolor: "rgb(240, 240, 240)", 
  plot_bgcolor: "rgb(240, 240, 240)", 
  hovermode: "x", 
  dragmode: "zoom", 
  separators: ".,", 
  barmode: "stack", 
  bargap: 0.2, 
  bargroupgap: 0.1, 
  boxmode: "overlay", 
  boxgap: 0.3, 
  boxgroupgap: 0.3, 
  hidesources: false
};
var graphOptions = {layout: layout};
plotly.plot(data, graphOptions, function (err, msg) {
    console.log(msg);
});